backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "work"
    label: "Work Item"
    folder: "src/pages/work-items"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "work-item",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: Name, name: name, widget: image }
          - {
              label: "Description",
              name: "description",
              widget: "string",
              required: false,
            }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: "Contact Box", name: contactBox, widget: markdown }
          - { label: Image, name: image, widget: image }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: "SEO Description", name: description, widget: string }
          - {
              label: Services,
              name: services,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: "Services List",
                    name: servicesList,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Title, name: title, widget: text },
                        { label: Description, name: description, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: "Latest Work",
              name: latestWork,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: "Testimonials List",
                    name: testimonialsList,
                    widget: list,
                    fields:
                      [
                        { label: Name, name: title, widget: string },
                        { label: Description, name: description, widget: text },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: ContentImage, name: contentImage, widget: image }
      - file: "src/pages/work/index.md"
        label: "Work"
        name: "work"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "work-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
